# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: paimon-web-configmap
  labels:
    app: paimon-web
data:
  application.yml: |-
    server:
      port: 10088
    spring:
      application:
        name: Paimon-Web-UI
      profiles:
        active: dev-mysql
      messages:
        basename: i18n/messages
        encoding: UTF-8
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
        format:
          date: yyyy-MM-dd HH:mm:ss # date format
          time: HH:mm:ss # time format
          date-time: yyyy-MM-dd HH:mm:ss # date-time format
      jackson:
        time-zone: GMT+8 # Time zone, default is GMT+8
        date-format: yyyy-MM-dd HH:mm:ss # Date format, the default is yyyy-MM-dd HH:mm:ss
        spring:
      datasource:
        url: jdbc:mysql://${MYSQL_ADDR:127.0.0.1:3306}/${MYSQL_DATABASE:paimon}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: ${MYSQL_USERNAME:username}
        password: ${MYSQL_PASSWORD:password}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 20
          minimum-idle: 10
          max-lifetime: 27000000
          idle-timeout: 600000
          connection-test-query: SELECT 1
    mybatis-plus:
      mapperLocations: classpath*:mapper/*Mapper.xml
      global-config:
        banner: false
        db-config:
          logic-delete-field: is_delete
      configuration:
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    sa-token:
      token-name: ${spring.application.name}
      timeout: 2592000
      active-timeout: -1
      is-concurrent: true
      is-share: true
      token-style: uuid
      is-log: false
      is-print: false
      is-read-cookie: true
      is-write-header: true
      is-read-header: true
      is-read-body: true
    management:
      web:
        exposure:
          include: info,health
      endpoint:
        health:
          show-details: when-authorized
      health:
        ldap:
          enabled: false

  log4j2-spring.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration status="OFF" monitorInterval="600">
        <Properties>
            <property name="LOG_PATH">./logs/</property>
            <property name="LOG_FILE">paimon</property>
            <property name="FILE_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss z} %-5level %class{36}#%M:%L - %msg%xEx%n"/>
            <property name="CONSOLE_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight{%6p} %style{%5pid}{bright,magenta} --- [%15.15t] %style{%c{20}}{bright,cyan}: %m%n"/>
        </Properties>
        <appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <ThresholdFilter level="info" onMatch="ACCEPT" onMismatch="ACCEPT"/>
                <PatternLayout>
                    <Pattern>${CONSOLE_LOG_PATTERN}</Pattern>
                </PatternLayout>
            </Console>
            
            <RollingFile name="RollingFile" fileName="${LOG_PATH}/${LOG_FILE}.log"
                         filePattern="${LOG_PATH}/$${date:yyyy-MM}/${LOG_FILE}-%d{yyyy-MM-dd}-%i.log">
                <PatternLayout>
                    <Pattern>${FILE_LOG_PATTERN}</Pattern>
                </PatternLayout>
                <Policies>
                    <TimeBasedTriggeringPolicy interval="1" modulate="true"/>
                    <SizeBasedTriggeringPolicy size="100MB"/>
                </Policies>
            </RollingFile>
        </appenders>
        
        <loggers>
            <root level="info">
                <appender-ref ref="Console"/>
                <!--<appender-ref ref="File"/>-->
                <appender-ref ref="RollingFile"/>
            </root>
        
        </loggers>
    </configuration>
     
     
